# Generated by Django 2.2.2 on 2019-06-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hotel_Main_Img',
            new_name='image',
        ),
    ]
