# Generated by Django 2.2.2 on 2019-06-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
