# Generated by Django 2.2.2 on 2019-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190709_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
