# Generated by Django 2.2.2 on 2019-07-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190709_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='/images/seulgi.jpg', upload_to='images/'),
        ),
    ]
